"""
Export Module — Exports rules in various formats.

Supports: DFA JSON, SSML XML, Regex TXT, and full ZIP bundle.
Uses io.BytesIO for streaming downloads (no temp files).
"""
import io
import json
import zipfile
from typing import Any


class Exporter:
    """Handles exporting rule bundles to downloadable file formats."""

    def export_dfa_json(self, dfa: dict[str, Any]) -> io.BytesIO:
        """Export DFA as a formatted JSON file."""
        content = json.dumps(dfa, indent=2, ensure_ascii=False)
        buffer = io.BytesIO(content.encode("utf-8"))
        buffer.seek(0)
        return buffer

    def export_ssml_xml(
        self, ssml: dict[str, Any], locale: str, category: str
    ) -> io.BytesIO:
        """Export SSML template as an XML file."""
        lang = locale.replace("_", "-")
        interpret_as = ssml.get("interpret_as", category)
        attributes = ssml.get("attributes", {})
        template = ssml.get("full_template", ssml.get("template", ""))

        attr_parts = []
        for key, value in attributes.items():
            attr_parts.append(f'{key}="{value}"')
        attr_string = " " + " ".join(attr_parts) if attr_parts else ""

        xml_content = (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<!--\n'
            f'  SSML Template for {category} normalization\n'
            f'  Locale: {locale}\n'
            f'  Generated by TTS Text Normalization Rule Engine\n'
            f'-->\n'
            f'<speak version="1.1"\n'
            f'  xmlns="http://www.w3.org/2001/10/synthesis"\n'
            f'  xml:lang="{lang}">\n'
            f'\n'
            f'  <!-- Template: replace {{value}} with normalized text -->\n'
            f'  {template}\n'
            f'\n'
            f'  <!-- Example usage -->\n'
            f'  <say-as interpret-as="{interpret_as}"{attr_string}>500</say-as>\n'
            f'\n'
            f'</speak>\n'
        )

        buffer = io.BytesIO(xml_content.encode("utf-8"))
        buffer.seek(0)
        return buffer

    def export_regex_txt(
        self, regex: dict[str, Any], locale: str, category: str
    ) -> io.BytesIO:
        """Export regex pattern as a text file with documentation."""
        pattern = regex.get("pattern", "")
        valid = regex.get("valid", True)

        txt_content = (
            f"# Text Normalization Regex Pattern\n"
            f"# =================================\n"
            f"# Locale:   {locale}\n"
            f"# Category: {category}\n"
            f"# Valid:    {valid}\n"
            f"# Generated by TTS Text Normalization Rule Engine\n"
            f"#\n"
            f"# Usage: Apply this regex with re.UNICODE flag\n"
            f"# Python: re.compile(pattern, re.UNICODE)\n"
            f"#\n\n"
            f"{pattern}\n"
        )

        buffer = io.BytesIO(txt_content.encode("utf-8"))
        buffer.seek(0)
        return buffer

    def export_zip_bundle(
        self, rules: dict[str, Any], locale: str, category: str
    ) -> io.BytesIO:
        """Export full rule bundle as a ZIP archive."""
        buffer = io.BytesIO()

        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            # DFA JSON
            dfa_content = json.dumps(rules.get("dfa", {}), indent=2, ensure_ascii=False)
            zf.writestr(f"dfa_{category}.json", dfa_content)

            # SSML XML
            ssml_buffer = self.export_ssml_xml(
                rules.get("ssml", {}), locale, category
            )
            zf.writestr(f"ssml_{category}.xml", ssml_buffer.read().decode("utf-8"))

            # Regex TXT
            regex_buffer = self.export_regex_txt(
                rules.get("regex", {}), locale, category
            )
            zf.writestr(f"regex_{category}.txt", regex_buffer.read().decode("utf-8"))

            # Full rules JSON (everything combined)
            full_content = json.dumps(rules, indent=2, ensure_ascii=False)
            zf.writestr(f"rules_{locale}_{category}.json", full_content)

            # README
            readme = (
                f"# Rule Bundle: {locale} / {category}\n\n"
                f"Generated by TTS Text Normalization Rule Engine\n\n"
                f"## Contents\n"
                f"- `dfa_{category}.json` — DFA state machine\n"
                f"- `ssml_{category}.xml` — SSML template\n"
                f"- `regex_{category}.txt` — Regex pattern\n"
                f"- `rules_{locale}_{category}.json` — Complete rule bundle\n"
            )
            zf.writestr("README.md", readme)

        buffer.seek(0)
        return buffer
